[project]
name = "electrical"
version = "0.1.0"
description = "Automation for interacting with kicad files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kiutils>=1.4.0",
]

[project.scripts]
kicad-utils = "kicad_utils:main"
